dist: trusty

env:
  global:
    - BASE_IMAGE_NAME=zazrivec/dcos-jupyterlab-service:latest
    - GPU_IMAGE_NAME=zazrivec/dcos-jupyterlab-service:latest-gpu
    - BASE_DATA_IMAGE_NAME=zazrivec/mesosphere-data-toolkit:latest
    - GPU_DATA_IMAGE_NAME=zazrivec/mesosphere-data-toolkit:latest-gpu

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t "$BASE_IMAGE_NAME" .
        - docker build -t "$GPU_IMAGE_NAME" -f Dockerfile-cuDNN .
        - docker build -t "$BASE_DATA_IMAGE_NAME" -f Dockerfile-data-toolkit .
        - docker push "$BASE_DATA_IMAGE_NAME"
        - docker build -t "$GPU_DATA_IMAGE_NAME" -f Dockerfile-data-toolkit-cuDNN .
        - docker push "$GPU_DATA_IMAGE_NAME"
